name: Deploy to GitHub pages
on: [push]
concurrency: 
  group: singleton
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: scottrules44/corona-container-doc-v2
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Checkout Submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1 --remote --merge
    - name: Build the docs
      working-directory: ./bin
      run: lua build.lua
    - name: Deploy Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: html
